### PR TITLE
Set response on form state instead of redirect URL

### PR DESCRIPTION
**Pull request by ricovandevin**
This should fix the issue in https://github.com/bartfeenstra/drupal-payment/issues/19.

### CODE REVIEW

**Comment by Berdir** [comment]
Makes sense.

**Comment by bartfeenstra** [comment]
Also great for responses that are not mere redirects! Thanks for digging into this.

I'm looking into fixing the Travis CI failures, so let's postpone the merge until that's done.

**Comment by ricovandevin** [comment]
Ok great.

I'm working quite a lot on payment methods the upcoming weeks so if I run into anything else I'll let you know.

**Comment by bartfeenstra** [comment]
Github rate limits should now no longer be a problem. Our Coveralls.io integration is still a pain, though, so it may have to go.

**Comment by bartfeenstra** [comment]
Travis CI works well now, with the exception of three failures caused by https://www.drupal.org/node/2615790. Would you be able to review the patch there and RTBC if it is alright?

**Comment by ricovandevin** [comment]
What is the status for this? I see that https://www.drupal.org/node/2615790 is fixed.

**Comment by bartfeenstra** [comment]
Let's run the tests again.

**Comment by bartfeenstra** [comment]
Please merge from 8.x-2.x and push, so the tests can run again.

**Comment by bartfeenstra** [comment]
Let's continue in https://github.com/bartfeenstra/drupal-payment/pull/31, which took this PR's original commit, and merged the latest 8.x-2.x into it.

**Pull request closed without merging**
