### PR TITLE
Changed Payer filter to consider usernames.

### PR DESCRIPTION
**Pull request by mbovan**

### CODE REVIEW

**Comment by Berdir** [comment]
This has a conflict now.

To explain this change , the current numeric filter results in a notice and we don't know exactly what's wrong. But switching to this, which is actually a lot better UX for users doesn't, so we thought that's the easiest way to fix this.

An integration test that enabled views and visits that page would be nice. I've also merged #2, this would also provide test coverage that the view is valid config.

**Comment by mbovan** [comment]
Rebased.

**Comment by mbovan** [comment]
I removed a key added by this PR which breaks schema and added one-line test for a username filter field as there is already test that visits /admin/content/payment path.

**Comment by Berdir** [comment]
Merged this. Improves the UI and fixes some notices. And gives us test coverage of the views integration.

**Pull request merged**
