### PR TITLE
Fix unit tests by chasing Drupal Core and Plugin

### PR DESCRIPTION
**Pull request by Berdir**
With this, at least the fatal error is gone, so the results can be fully shown and parsed again, by http://d8status.md-systems.ch/ for example.

### CODE REVIEW

**Comment by Berdir** [comment]
Well, now the problem is that there is so much noise from those unit test fails that the simpletest results are not even visible anymore :(

**Comment by bartfeenstra** [comment]
We must make sure that all `@return` documentation matches the given output. When updating Currency to make sure it works with `StringTranslationTrait::t()` outputting `TranslatableMarkup` I noticed that some core interfaces such as `FilterInterface` still document translated strings must be returned instead of `TranslatableMarkup`. Is the documentation out of date, or should the translation be converted to a string before being returned?

**Comment by Berdir** [comment]
out of date. those strings must _not_ be converted, as that might break escaping of links.

**Comment by bartfeenstra** [comment]
Thanks for confirming. This means Currency needs some more love, as I followed the interfaces.

**Comment by bartfeenstra** [comment]
Thanks for kicking this off!

**Pull request merged**
